class Country

  def self.list
    {
######################################################
  "Asia" => {
######################################################
"Afghanistan" => "af",
"Bangladesh" => "bd",
"Bhutan" => "bt",
"Brunei Darussalam" => "bn",
"Cambodia" => "kh",
"China" => "cn",
#                           "Christmas Island" => "cx",
"Cocos Islands" => "cc",
#"Hong Kong" => "hk",
"India" => "in",
"Indonesia" => "id",
"Japan" => "jp",
"Kazakhstan" => "kz",
"North Korea" => "kp",
"South Korea" => "kr",
"Kyrgyzstan" => "kg",
"Laos" => "la",
#                           "Macao" => "mo",
"Malaysia" => "my",
"Maldives" => "mv",
"Mongolia" => "mn",
"Myanmar" => "mm",
"Nepal" => "np",
"Pakistan" => "pk",
"Philippines" => "ph",
"Singapore" => "sg",
"Sri Lanka" => "lk",
"Taiwan" => "tw",
"Tajikistan" => "tj",
"Thailand" => "th",
"East Timor" => "tl",
"Turkmenistan" => "tm",
"Uzbekistan" => "uz",
"Vietnam" => "vn"
  },

######################################################
  "Middle East" => {
######################################################
"Bahrain" => "bh",
"Iran" => "ir",
"Iraq" => "iq",
"Israel" => "il",
"Jordan" => "jo",
"Kuwait" => "kw",
"Lebanon" => "lb",
#"Palestinian Territory" => "ps",
"Oman" => "om",
"Qatar" => "qa",
"Saudi Arabia" => "sa",
"Syria" => "sy",
"United Arab Emirates" => "ae",
"Yemen" => "ye"
  },

######################################################
  "Europe" => {
######################################################
"Albania" => "al",
"Andorra" => "ad",
"Armenia" => "am",
"Austria" => "at",
"Azerbaijan" => "az",
"Belarus" => "by",
"Belgium" => "be",
"Bosnia and Herzegovina" => "ba",
"Bulgaria" => "bg",
"Croatia" => "hr",
"Cyprus" => "cy",
"Czech Republic" => "cz",
"Denmark" => "dk",
#"England" => "gb",
"Estonia" => "ee",
#"Faroe Islands" => "fo",
"Finland" => "fi",
"France" => "fr",
"Georgia" => "ge",
"Germany" => "de",
"Great Britain" => "gb",
#"Gibraltar" => "gi",
"Greece" => "gr",
"Greenland" => "gl",
"Guernsey" => "gg",
"Hungary" => "hu",
"Iceland" => "is",
"Ireland" => "ie",
#"Isle Of Man" => "im",
"Italy" => "it",
"Jersey" => "je",
"Latvia" => "lv",
"Liechtenstein" => "li",
"Lithuania" => "lt",
"Luxembourg" => "lu",
"Macedonia" => "mk",
"Malta" => "mt",
"Moldova" => "md",
"Monaco" => "mc",
"Montenegro" => "me",
"Netherlands" => "nl",
"Norway" => "no",
"Poland" => "pl",
"Portugal" => "pt",
"Romania" => "ro",
"Russia" => "ru",
#"San Marino" => "sm",
"Serbia" => "rs",
"Slovakia" => "sk",
"Slovenia" => "si",
"Spain" => "es",
#"Svalbard And Jan Mayen" => "sj",
"Sweden" => "se",
"Switzerland" => "ch",
"Turkey" => "tr",
"Ukraine" => "ua",
"Vatican City" => "va"},

######################################################
  "Central America" => {
######################################################
"Belize" => "bz",
"Costa Rica" => "cr",
"El Salvador" => "sv",
"Guatemala" => "gt",
"Honduras" => "hn",
"Nicaragua" => "ni",
"Panama" => "pa"
  },

######################################################
  "Caribbean Islands" => {
######################################################
"Anguilla" => "ai",
"Antigua and Barbuda" => "ag",
"Aruba" => "aw",
"Bahamas" => "bs",
"Barbados" => "bb",
"Bermuda" => "bm",
"British Virgin Islands" => "vg",
"US Virgin Islands" => "vi",
"Cayman Islands" => "ky",
"Cuba" => "cu",
"Dominica" => "dm",
"Dominican Republic" => "do",
"Grenada" => "gd",
"Guadeloupe" => "gp",
"Haiti" => "ht",
"Jamaica" => "jm",
"Martinique" => "mq",
"Montserrat" => "ms",
"Netherlands Antilles" => "an",
"Puerto Rico" => "pr",
"St Barthelemy" => "bl",
"St Kitts and Nevis" => "kn",
"St Lucia" => "lc",
"St Martin" => "mf",
"St Pierre and Miquelon" => "pm",
"St Vincent and The Grenadines" => "vc",
"Trinidad and Tobago" => "tt",
"Turks and Caicos" => "tc"
  },

######################################################
  "North America" => {
######################################################
"Canada" => "ca",
"Mexico" => "mx",
"United States" => "us"
#"United States Minor Outlying Islands" => "um"
  },

######################################################
  "South America" => {
######################################################
"Argentina" => "ar",
"Bolivia" => "bo",
"Brazil" => "br",
"Chile" => "cl",
"Colombia" => "co",
"Ecuador" => "ec",
"Falkland Islands (Malvinas)" => "fk",
"French Guiana" => "gf",
"Paraguay" => "py",
"Peru" => "pe",
"The Guyanas" => "gy",
"Suriname" => "sr",
"Uruguay" => "uy",
"Venezuela" => "ve"
  },

######################################################
  "Africa" => {
######################################################
"Algeria" => "dz",
"Angola" => "ao",
#                         "Aland Islands" => "ax",
"Benin" => "bj",
"Botswana" => "bw",
"Burkina Faso" => "bf",
"Burundi" => "bi",
"Cameroon" => "cm",
"Cape Verde" => "cv",
"Central African Republic" => "cf",
"Chad" => "td",
"Comoros" => "km",
"Congo" => "cg",
"DR Congo" => "cd",
"Cote D'Ivoire" => "ci",
"Djibouti" => "dj",
"Egypt" => "eg",
"Equatorial Guinea" => "gq",
"Eritrea" => "er",
"Ethiopia" => "et",
"Gabon" => "ga",
"The Gambia" => "gm",
"Ghana" => "gh",
"Guinea" => "gn",
"Guinea-Bissau" => "gw",
"Kenya" => "ke",
"Lesotho" => "ls",
"Liberia" => "lr",
"Libya" => "ly",
"Madagascar" => "mg",
"Malawi" => "mw",
"Mali" => "ml",
"Mauritania" => "mr",
"Mauritius" => "mu",
"Mayotte" => "yt",
"Morocco" => "ma",
"Mozambique" => "mz",
"Namibia" => "na",
"Niger" => "ne",
"Nigeria" => "ng",
"Reunion" => "re",
"Rwanda" => "rw",
"Saint Helena" => "sh",
"Sao Tome and Principe" => "st",
"Senegal" => "sn",
"Seychelles" => "sc",
"Sierra Leone" => "sl",
"Somalia" => "so",
"South Africa" => "za",
# South Sudan
"Sudan" => "sd",
"Swaziland" => "sz",
"Tanzania" => "tz",
"Togo" => "tg",
"Tunisia" => "tn",
"Uganda" => "ug",
#                       "Western Sahara" => "eh",
"Zambia" => "zm",
"Zimbabwe" => "zw"},

#######################################################
  "Australia/Oceania" => {
"American Samoa" => "as",
"Australia" => "au",
"Fiji" => "fj",
"French Polynesia" => "pf",
"Guam" => "gu",
"Kiribati" => "ki",
"Marshall Islands" => "mh",
"Federated States of Micronesia" => "fm",
"Nauru" => "nr",
"New Caledonia" => "nc",
"New Zealand" => "nz",
"Niue" => "nu",
#"Norfolk Island" => "nf",
"Northern Mariana Islands" => "mp",
"Palau" => "pw",
"Papua New Guinea" => "pg",
"Pitcairn" => "pn",
"Rarotonga & Cook Islands" => "ck",
"Samoa" => "ws",
"Solomon Islands" => "sb",
"Tokelau" => "tk",
"Tonga" => "to",
"Tuvalu" => "tv",
"Vanuatu" => "vu",
"Wallis And Futuna" => "wf" }
    }
  end
end
